STORIES_SERVICE_IP = '172.28.1.2'
STORIES_SERVICE_PORT = '5000'

USERS_SERVICE_IP = '172.28.1.3'
USERS_SERVICE_PORT = '5000'

DICE_SERVICE_IP = '172.28.1.4'
DICE_SERVICE_PORT = '5000'

PROFILING_SERVICE_IP = '172.28.1.5'
PROFILING_SERVICE_PORT = '5000'

REACTIONS_SERVICE_IP = '172.28.1.6'
REACTIONS_SERVICE_PORT = '5000'

SEARCH_USER_URL = "http://{}:{}/search".format(USERS_SERVICE_IP, USERS_SERVICE_PORT) # add search key to end of the string by using format

SEARC_STORIES_URL = "http://{}:{}/search_story".format(STORIES_SERVICE_IP,STORIES_SERVICE_PORT) #add search key to end of the string by using format