openapi: 3.0.0
info:
  version: 1.0.0
  title: SocialDice Users Service

paths:
  /search:
     post:
      summary: "Search user and stories on services"
      description: ""
      operationId: "search"

      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                search_text:
                    type: string


      responses:
        '200':
          description: A JSON string with a response message
          content:
            application/json:
              schema:
                type: object
                properties:
                  users:
                    type: object
                  stories:
                    type: object


